### ISSUE TITLE
Add git switch -c to Branching

### ISSUE THREAD

**Issue by MisterMountain** [NETWAYS/gitlab-training#212]
In the Git-Branching Part of the trainings Day 1 we still use `git branch newbranch` and then `git checkout newbranch`.
Maybe it would be a good idea to also suggest using `git switch -c newbranch` as this basically does both things at once.

**Comment by martialblog** [comment]
This is by design, we're introducing the `git branch` and the `git checkout` command separately to show their existence and functions. In the "Create and checkout a new branch" we show `git checkout -b feature/docs2`

We sometimes show `git switch` during the training, however, since it's still experimental (see manpage) we do not rely on it yet.
